Fixes #1 - timeago filter: if there is no hours do not show 'X hours ago'
flagshipcompany/twig-extensions pull request #2
Opened 2017-04-05 20:13 UTC by Binita710

2017-04-07 19:33 UTC, patrick-fls requested changes

2017-04-07 19:33 UTC, patrick-fls commented on src/Filters/TimeAgoFilter.php
> +        if ($date == date('Y-m-d', strtotime(('-1 day'))) && $dateDetails['hour'] == false) {
Switch the conditions around. It won't parse the date and do the math if the first condition is false, which makes it more performant.

2017-04-12 16:00 UTC, jason-FLS requested changes

2017-04-12 16:00 UTC, jason-FLS commented on src/Filters/TimeAgoFilter.php
>              $numberOfUnits = floor($time / $unit);
Its unrelated to this ticket, but switch this to a `ceil` function

2017-04-12 19:08 UTC, jason-FLS approved these changes

2017-04-12 21:00 UTC, merged